CREATE TABLE Contact(
    id INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(60) NOT NULL
    , BIRTH_DATE DATE
    , VERSION INT NOT NULL DEFAULT 0
    , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (id)
);

CREATE TABLE Contact_Audit(
    id INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(60) NOT NULL
    , BIRTH_DATE DATE
    , VERSION INT NOT NULL DEFAULT 0
    , CREATED_BY VARCHAR(20)
    , CREATED_DATE TIMESTAMP
    , LAST_MODIFIED_BY VARCHAR(20)
    , LAST_MODIFIED_DATE TIMESTAMP
    , UNIQUE UQ_CONTACT_AUDIT_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (id)
);

CREATE TABLE Contact_Audit_H(
    id INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(60) NOT NULL
    , BIRTH_DATE DATE
    , VERSION INT NOT NULL DEFAULT 0
    , CREATED_BY VARCHAR(20)
    , CREATED_DATE TIMESTAMP
    , LAST_MODIFIED_BY VARCHAR(20)
    , LAST_MODIFIED_DATE TIMESTAMP
    , AUDIT_REVISION INT NOT NULL
    , ACTION_TYPE INT
    , AUDIT_REVISION_END INT
    , AUDIT_REVISION_END_TS TIMESTAMP
    , UNIQUE UQ_CONTACT_AUDIT_H_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (id, AUDIT_REVISION)
);

CREATE TABLE REVINFO(
    REVTSTMP BIGINT NOT NULL
    , REV INT NOT NULL AUTO_INCREMENT 
    , PRIMARY KEY (REVTSTMP, REV)
);

CREATE TABLE Hobby(
    hobby_id VARCHAR(20) NOT NULL 
    , PRIMARY KEY (hobby_id)
);

CREATE TABLE Contact_tel_detail(
    id INT NOT NULL AUTO_INCREMENT
    , CONTACT_ID INT NOT NULL
    , TEL_TYPE VARCHAR(20) NOT NULL
    , TEL_NUMBER VARCHAR(20) NOT NULL
    , VERSION INT NOT NULL DEFAULT 0
    , UNIQUE UQ_CONTACT_TEL_DETAIL_1 (CONTACT_ID, TEL_TYPE)
    , PRIMARY KEY (ID)
    , CONSTRAINT FK_CONTACT_TEL_DETAIL_1 FOREIGN KEY (CONTACT_ID)
        REFERENCES Contact(id)
);

CREATE TABLE Contact_hobby_detail(
    contact_id INT NOT NULL
    , hobby_id VARCHAR(20) NOT NULL
    , PRIMARY KEY (contact_id, hobby_id)
    , CONSTRAINT FK_CONTACT_HOBBY_DETAIL_1 FOREIGN KEY (contact_id)
        REFERENCES CONTACT(id) ON DELETE CASCADE
    , CONSTRAINT FK_CONTACT_HOBBY_DETAIL_2 FOREIGN KEY (hobby_id)
        REFERENCES Hobby(hobby_id)
);